package creature

// Pixel maps of the mushroom. K ink, P paper, G moss, H honey, R accent,
// . transparent. It follows the same rules as mossArt: the face (two eyes,
// blush and a mouth) goes on the honey cap, the paper is the gills under the
// cap, the stem is moss, the scarf wraps the stem and the hat and the flower
// sit on the cap.
var mushroomArt = [...]stageArt{
	Seed: {
		body: [Size]string{
			"................",
			"................",
			"................",
			"................",
			"................",
			"......KKKK......",
			"....KKHHHHKK....",
			"...KHHHPPHHHK...",
			"...KHHHHHHHHK...",
			"...KHHHHHHHHK...",
			"...KHHHHHHHHK...",
			"...KHHHHHHHHK...",
			"..KKKKKKKKKKKK..",
			"....KGGGGGGK....",
			"....KGGGGGGK....",
			"....KKKKKKKK....",
		},
		face:      Point{4, 8},
		hat:       Point{5, 2},
		scarfRow:  13,
		scarfTail: Point{9, 14},
		flower:    Point{11, 4},
	},
	Sprout: {
		body: [Size]string{
			"................",
			"................",
			"................",
			"................",
			"......KKKK......",
			"....KKHHHHKK....",
			"..KKHHPPHHHHKK..",
			".KHHHHHPHHHHHHK.",
			".KHHHHHHHHHHHHK.",
			".KHHHHHHHHHHHHK.",
			".KHHHHHHHHHHHHK.",
			".KHHHHHHHHHHHHK.",
			"..KKKKKKKKKKKK..",
			"....KGGGGGGK....",
			"....KGGGGGGK....",
			"....KKKKKKKK....",
		},
		face:      Point{4, 7},
		hat:       Point{5, 1},
		scarfRow:  13,
		scarfTail: Point{9, 14},
		flower:    Point{12, 2},
	},
	Sapling: {
		body: [Size]string{
			"................",
			"......KKKK......",
			"....KKHHHHKK....",
			"..KKHHHPPHHHKK..",
			".KHHHHHHPHHHHHK.",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			".KHHHHHHHHHHHHK.",
			"..KKKKKKKKKKKK..",
			"...KPPPPPPPPK...",
			"....KGGGGGGK....",
			"....KGGGGGGK....",
			"....KGGGGGGK....",
			"...KKKKKKKKKK...",
		},
		face:      Point{4, 5},
		hat:       Point{5, 0},
		scarfRow:  12,
		scarfTail: Point{9, 13},
		flower:    Point{12, 1},
	},
	Shrub: {
		body: [Size]string{
			"....KKKKKKKK....",
			"..KKHHHHHHHHKK..",
			".KHHHPPHHHHHHHK.",
			"KHHHHHHPHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			".KHHHHHHHHHHHHK.",
			"..KKKKKKKKKKKK..",
			"...KPPPPPPPPK...",
			"....KGGGGGGK....",
			"....KGGGGGGK....",
			".KK.KGGGGGGK....",
			"KHHKKGGGGGGK....",
			"KKKKKKKKKKKKKKK.",
		},
		face:      Point{4, 5},
		hat:       Point{5, 0},
		scarfRow:  11,
		scarfTail: Point{9, 12},
		flower:    Point{11, 0},
	},
	Ancient: {
		body: [Size]string{
			"....KKKKKKKK....",
			"..KKHHHHHHHHKK..",
			".KHHHPPHHHHHHHK.",
			"KHHHHHHPHHHHHGGK",
			"KGGHHHHHHHHHHHGK",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHHHK",
			"KHHHHHHHHHHHHGGK",
			".KHHHHHHHHHHHHK.",
			"..KKKKKKKKKKKK..",
			"...KPPPPPPPPK...",
			"....KGGGGGGK....",
			".KK.KGGGGGGK.KK.",
			"KHHKKGGGGGGKKHHK",
			".KGKKGGGGGGKKGK.",
			"KKKKKKKKKKKKKKKK",
		},
		face:      Point{4, 5},
		hat:       Point{5, 0},
		scarfRow:  11,
		scarfTail: Point{9, 12},
		flower:    Point{11, 0},
	},
}
